#include "stdafx.h"
#include "AssetManager.h"
#include "../ModelLoader/ModelLoader.h"
#include "../../Model/Model.h"
#include "../../Model/ModelMaterial.h"
#include "../../Model/ModelMesh.h"
#include "../../Model/Animation/ModelAnimation.h"
#include "../../Model/Animation/ModelAnimationKeyFrames.h"
#include "../../Model/Animation/ModelAnimationController.h"
#include "../../Model/Skeleton/ModelSkeleton.h"
#include "../../Model/Skeleton/ModelSkeletonBone.h"

#include "./GameCore/Resource/Mesh.h"
#include "./GameCore/Resource/Material.h"
#include "./GameCore/GameObject/Components/Renderer/MeshFilter.h"
#include "./GameCore/GameObject/Components/Renderer/Renderer.h"
#include "./GameCore/GameObject/Components/Renderer/SkinnedMeshRenderer.h"
#include "./GameCore/GameObject/Components/Animator/Animator.h"

#include "./GameCore/GameObject/Components/Transform.h"
#include "./GameCore/Collider/ColliderMan